services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    command: gunicorn prowler_scanner.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0

  db:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    platform: linux/amd64
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    command: celery -A prowler_scanner worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    command: celery -A prowler_scanner beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
